<?php

// Generated by Haxe 3.4.4
class Index {
	public function __construct($r) {
		if(!php_Boot::$skip_constructor) {
		$this->request = $r;
	}}
	public $request;
	public function doUser($reference = null) {
		controllers_UserController::dispatch($this->request, $reference);
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	static function __meta__() { $args = func_get_args(); return call_user_func_array(self::$__meta__, $args); }
	static $__meta__;
	static function main() {
		controller_Listener::boot();
	}
	static function dispatch($request) {
		try {
			sys_db_Manager::initialize();
			sys_db_Manager::set_cnx(php_db_PDO::open("mysql:host=localhost;dbname=covoit_afg", "sqlfchevalier", "savary", null));
			if(!sys_db_TableCreate::exists(models_Eleves::$manager)) {
				sys_db_TableCreate::create(models_Eleves::$manager, null);
				sys_db_TableCreate::create(models_Trajet::$manager, null);
			}
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			$e = $_ex_;
			{
				$request->setReturnCode(503, "Erreur DataBase ");
				return;
			}
		}
		try {
			$tmp = new haxe_web_Dispatch($request->query, null);
			$tmp1 = haxe_web_Dispatch::extractConfig(new Index($request));
			$tmp->runtimeDispatch($tmp1);
		}catch(Exception $__hx__e) {
			$_ex_ = ($__hx__e instanceof HException) && $__hx__e->getCode() == null ? $__hx__e->e : $__hx__e;
			if(($e1 = $_ex_) instanceof haxe_web_DispatchError){
				$request->setReturnCode(406, "Not Acceptable");
			}
			else { $e2 = $_ex_;
			{
				$request->setReturnCode(500, Std::string($e2));
			}}
		}
		sys_db_Manager::cleanup();
	}
	function __toString() { return 'Index'; }
}
Index::$__meta__ = _hx_anonymous(array("obj" => _hx_anonymous(array("dispatchConfig" => (new _hx_array(array("oy4:userjy21:haxe.web.DispatchRule:0:1jy18:haxe.web.MatchRule:8:1jR2:3:0g")))))));
