<?php

// Generated by Haxe 3.4.4
class models_Eleves extends sys_db_Object {
	public function __construct($nom, $prenom, $mail, $telephone, $mdp, $id = null) {
		if(!php_Boot::$skip_constructor) {
		parent::__construct();
		$this->nom = $nom;
		$this->prenom = $prenom;
		$this->mail = $mail;
		$this->telephone = $telephone;
		$this->mdp = $mdp;
		if($id === null) {
			$this->idEleves = models_Helped::genUUID();
		} else {
			$this->idEleves = $id;
		}
	}}
	public $idEleves;
	public $nom;
	public $prenom;
	public $mail;
	public $telephone;
	public $mdp;
	public function __getManager() {
		return models_Eleves::$manager;
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	static function __meta__() { $args = func_get_args(); return call_user_func_array(self::$__meta__, $args); }
	static $__meta__;
	static $manager;
	function __toString() { return 'models.Eleves'; }
}
models_Eleves::$__meta__ = _hx_anonymous(array("obj" => _hx_anonymous(array("rtti" => (new _hx_array(array("oy4:namey6:Elevesy7:indexesahy9:relationsahy7:hfieldsby3:nomoR0R5y6:isNullfy1:tjy17:sys.db.RecordType:9:1i30gy9:telephoneoR0R9R6fR7jR8:9:1i10gy6:prenomoR0R10R6fR7jR8:9:1i30gy8:idElevesoR0R11R6fR7jR8:9:1i36gy4:mailoR0R12R6fR7jR8:9:1i50gy3:mdpoR0R13R6fR7jR8:9:1i64ghy3:keyaR11hy6:fieldsar10r4r8r12r6r14hg")))))));
models_Eleves::$manager = new sys_db_Manager(_hx_qtype("models.Eleves"));
