<?php

// Generated by Haxe 3.4.4
class models_Trajet extends sys_db_Object {
	public function __construct($idTrajet, $heure, $km, $dte, $jour, $type, $idEleve) {
		if(!php_Boot::$skip_constructor) {
		parent::__construct();
		$this->idTrajet = $idTrajet;
		$this->heure = $heure;
		$this->km = $km;
		$this->dte = $dte;
		$this->jour = $jour;
		$this->type = $type;
		$this->set_idEleve($idEleve);
	}}
	public $idEleve;
	public $idTrajet;
	public $heure;
	public $km;
	public $dte;
	public $jour;
	public $type;
	public function get_idEleve() {
		return models_Eleves::$manager->h__get($this, "idEleve", "idEleves", false);
	}
	public function set_idEleve($_v) {
		return models_Eleves::$manager->h__set($this, "idEleve", "idEleves", $_v);
	}
	public $idEleves;
	public function __getManager() {
		return models_Trajet::$manager;
	}
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	static function __meta__() { $args = func_get_args(); return call_user_func_array(self::$__meta__, $args); }
	static $__meta__;
	static $manager;
	static $__properties__ = array("set_idEleve" => "set_idEleve","get_idEleve" => "get_idEleve");
	function __toString() { return 'models.Trajet'; }
}
models_Trajet::$__meta__ = _hx_anonymous(array("obj" => _hx_anonymous(array("rtti" => (new _hx_array(array("oy4:namey6:Trajety7:indexesahy9:relationsaoy6:moduley13:models.Elevesy4:lockfy4:propy7:idElevey4:typeR5y7:cascadefy6:isNullfy3:keyy8:idElevesghy7:hfieldsby2:kmoR0R15R11fy1:tjy17:sys.db.RecordType:7:0gR9oR0R9R11fR16jR17:8:0gy5:heureoR0R18R11fR16jR17:9:1i30gy4:jouroR0R19R11fR16jR17:9:1i5gR13oR0R13R11fR16jR17:9:1i50gy3:dteoR0R20R11fR16jR17:11:0gy8:idTrajetoR0R21R11fR16jR17:9:1i50ghR12aR21hy6:fieldsar17r9r5r15r11r7r13hg")))))));
models_Trajet::$manager = new sys_db_Manager(_hx_qtype("models.Trajet"));
