<?php

// Generated by Haxe 3.4.4
class controllers_UserController {
	public function __construct(){}
	static function dispatch($request, $reference) {
		$tmp = null;
		if($reference === "all") {
			$tmp = $request->method === "GET";
		} else {
			$tmp = false;
		}
		if($tmp) {
			controllers_UserController::retrieveAll($request);
		} else {
			$tmp1 = null;
			if($request->method !== "POST") {
				$tmp1 = $reference === null;
			} else {
				$tmp1 = false;
			}
			if($tmp1) {
				$request->setReturnCode(406, "Not Acceptable\x0Amissing reference");
			} else {
				$request->setReturnCode(501, "Not implement");
			}
		}
	}
	static function retrieveAll($request) {
		$elevesInDB = Lambda::harray(models_Eleves::$manager->all(null));
		$request->setHeader("Content-Type", "application/json");
		$request->send(haxe_Json::phpJsonEncode($elevesInDB, null, null));
	}
	function __toString() { return 'controllers.UserController'; }
}
