<?php

// Generated by Haxe 3.4.4
class controllers_UserController {
	public function __construct(){}
	static function dispatch($request, $reference) {
		$tmp = null;
		if($reference === "all") {
			$tmp = $request->method === "GET";
		} else {
			$tmp = false;
		}
		if($tmp) {
			controllers_UserController::retrieveAll($request);
		} else {
			$tmp1 = null;
			if($request->method !== "POST") {
				$tmp1 = $reference === null;
			} else {
				$tmp1 = false;
			}
			if($tmp1) {
				$request->setReturnCode(406, "Not Acceptable\x0Amissing reference");
			} else {
				switch($request->method) {
				case "DELETE":{
					controllers_UserController::deleteUser($request, $reference);
				}break;
				case "GET":{
					controllers_UserController::retrieveOne($request, $reference);
				}break;
				case "POST":{
					controllers_UserController::postUser($request, $reference);
				}break;
				case "PUT":{
					controllers_UserController::updateUser($request, $reference);
				}break;
				default:{
					$request->setReturnCode(501, "Not implement");
				}break;
				}
			}
		}
	}
	static function retrieveAll($request) {
		$userInDB = Lambda::harray(models_User::$manager->all(null));
		$request->setHeader("Content-Type", "application/json");
		$request->send(haxe_Json::phpJsonEncode($userInDB, null, null));
	}
	static function retrieveOne($request, $idUser) {
		$request->setHeader("Content-Type", "application/json");
		$user = models_User::$manager->unsafeGet($idUser, true);
		if($user === null) {
			$request->setReturnCode(404, "User not found for idUser " . _hx_string_or_null($idUser));
			return;
		}
		$request->send(haxe_Json::phpJsonEncode($user, null, null));
	}
	static function postUser($request, $idUser) {
		$data = $request->data;
		$u = null;
		$tmp = null;
		if($data->login !== null) {
			$tmp = !Std::is($data->login, _hx_qtype("String"));
		} else {
			$tmp = true;
		}
		if($tmp) {
			$request->setReturnCode(400, "Bad login");
			return;
		}
		$tmp1 = null;
		if($data->nom !== null) {
			$tmp1 = !Std::is($data->nom, _hx_qtype("String"));
		} else {
			$tmp1 = true;
		}
		if($tmp1) {
			$request->setReturnCode(400, "Bad nom");
			return;
		}
		$tmp2 = null;
		if($data->prenom !== null) {
			$tmp2 = !Std::is($data->prenom, _hx_qtype("String"));
		} else {
			$tmp2 = true;
		}
		if($tmp2) {
			$request->setReturnCode(400, "Bad nom");
			return;
		}
		$tmp3 = null;
		if($data->mail !== null) {
			$tmp3 = !Std::is($data->mail, _hx_qtype("String"));
		} else {
			$tmp3 = true;
		}
		if($tmp3) {
			$request->setReturnCode(400, "Bad mail");
			return;
		}
		$tmp4 = null;
		if($data->telephone !== null) {
			$tmp4 = !Std::is($data->telephone, _hx_qtype("String"));
		} else {
			$tmp4 = true;
		}
		if($tmp4) {
			$request->setReturnCode(400, "Bad telephone");
			return;
		}
		$tmp5 = null;
		if($data->mdp !== null) {
			$tmp5 = !Std::is($data->mdp, _hx_qtype("String"));
		} else {
			$tmp5 = true;
		}
		if($tmp5) {
			$request->setReturnCode(400, "Bad mdp");
			return;
		}
		$u = new models_User($data->login, $data->nom, $data->prenom, $data->mail, $data->telephone, $data->mdp, $idUser);
		$u->insert();
		$request->setHeader("Content-Type", "application/json");
		$request->send("{\"idUser\":\"" . _hx_string_or_null($u->idUser) . "\"}");
	}
	static function updateUser($request, $idUser) {
		$data = $request->data;
		$u = models_User::$manager->unsafeGet($idUser, true);
		if($u === null) {
			$request->setReturnCode(404, "Eleve not found");
			return;
		}
		$tmp = null;
		if($data->login !== null) {
			$tmp = !Std::is($data->login, _hx_qtype("String"));
		} else {
			$tmp = true;
		}
		if($tmp) {
			$request->setReturnCode(400, "Bad login");
			return;
		}
		$tmp1 = null;
		if($data->nom !== null) {
			$tmp1 = !Std::is($data->nom, _hx_qtype("String"));
		} else {
			$tmp1 = true;
		}
		if($tmp1) {
			$request->setReturnCode(400, "Bad nom");
			return;
		}
		$u->nom = $data->nom;
		$tmp2 = null;
		if($data->prenom !== null) {
			$tmp2 = !Std::is($data->prenom, _hx_qtype("String"));
		} else {
			$tmp2 = true;
		}
		if($tmp2) {
			$request->setReturnCode(400, "Bad prenom");
			return;
		}
		$u->prenom = $data->prenom;
		$tmp3 = null;
		if($data->mail !== null) {
			$tmp3 = !Std::is($data->mail, _hx_qtype("String"));
		} else {
			$tmp3 = true;
		}
		if($tmp3) {
			$request->setReturnCode(400, "Bad mail");
			return;
		}
		$u->mail = $data->mail;
		$tmp4 = null;
		if($data->telephone !== null) {
			$tmp4 = !Std::is($data->telephone, _hx_qtype("String"));
		} else {
			$tmp4 = true;
		}
		if($tmp4) {
			$request->setReturnCode(400, "Bad telephone");
			return;
		}
		$u->telephone = $data->telephone;
		$tmp5 = null;
		if($data->mdp !== null) {
			$tmp5 = !Std::is($data->mdp, _hx_qtype("String"));
		} else {
			$tmp5 = true;
		}
		if($tmp5) {
			$request->setReturnCode(400, "Bad mdp");
			return;
		}
		$u->mdp = $data->mdp;
		$u->update();
	}
	static function deleteUser($request, $idUser) {
		$u = models_User::$manager->unsafeGet($idUser, true);
		if($u === null) {
			$request->setReturnCode(404, "Eleve not found");
			return;
		}
		$u->delete();
	}
	function __toString() { return 'controllers.UserController'; }
}
